language: python
cache:
  directories:
    - "${HOME}/virtualenv"
    - "${TRAVIS_BUILD_DIR}/.tox"

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install tox

script:
  - tox
  - "find ${TRAVIS_BUILD_DIR}/.tox -name log -o -name __pycache__ -type d | xargs -I {} rm -rf {}"
  - pytest --cov=app/