language: python
sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker build -t artyom/elasticui .

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov pytest-flask coverage
  - pip install codecov

before_script:
  - docker-compose -f docker-compose-ci.yaml up -d --force-recreate

script:
  - py.test --cov=app

after_success:
  - coverage xml
  - codecov

after_script:
  - docker-compose down