language: python
notifications:
  email: false
sudo: false
python:
  - 2.7

matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-requests
            - python-coverage
            - python-mock

install:
  - pip install -r requirements.txt
script:
  - py.test --cov=app
after_success:
  - codecov --token=9ae23f35-0e87-4fb2-ab0f-8150398bb408