language: python
notifications:
  email: false
sudo: false
python:
  - 2.7
  - pypy
  - 3.4
  - 3.5
  - 3.6
  - pypy3
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-requests
            - python-coverage
            - python-mock

install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - py.test tests/unit/test_web.py --cov=app
after_success:
  - codecov