language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34

install:
  - pip install wheel codecov coverage
  - pip install -r requirements.txt
  - pip install tox tox-travis
  - python setup.py bdist_wheel
  - pip install ./dist/tox_travis-*.whl

script: tox --installpkg ./dist/tox_travis-*.whl
after_success: coverage combine && codecov