language: python

before_install:
  - source ~/virtualenv/python3.5/bin/activate

virtualenv:
  system_site_packages: true

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=app/