version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - ./custom_queue.conf:/application/config/custom_queue.conf
    links:
     - queue
  queue:
      image: s12v/elasticmq
      volumes:
        - ./custom_queue.conf:/etc/elasticmq/elasticmq.conf
      ports:
        - "9324:9324"